### ISSUE TITLE
 supportPKCE return value is incorrect

### ISSUE THREAD

**Issue by mo36924** [panva/openid-client#710]
### What happened?

supportsPKCE return value is incorrect.

https://github.com/panva/openid-client/blob/ff1436ea991d771b0257a7c12752621ae6abaaf9/src/index.ts#L1464-L1472

The following code may be more correct.
```typescript
metadata.code_challenge_methods_supported?.includes(method) === true 
```

### Version

v6.1.0

### Runtime

Node.js

### Runtime Details

v20.17.0

### Code to reproduce

```js
import { equal } from "node:assert";
import { discovery } from "openid-client";

const config = await discovery(new URL("https://accounts.google.com"), "clientId", "clientSecret");
equal(config.serverMetadata().code_challenge_methods_supported?.includes("S256"), true);
// The following line throws an error
equal(config.serverMetadata().supportsPKCE(), true);
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/openid-client/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Fixed in https://github.com/panva/openid-client/releases/tag/v6.1.1
