### ISSUE TITLE
No possibility to manually input a redirectUri anymore

### ISSUE THREAD

**Issue by wzrdtales** [panva/openid-client#727]
### What happened?

It seems according to the code, that it is not possible anymore to pass the redirectUrl directly.

https://github.com/panva/openid-client/blob/90eb7056a39ec3f3ec63e81e19689f6f559eddf9/src/index.ts#L2550

This breaks any API who process the request after a redirect that retained the query params. Which is a quite common scenario. It should be still possible to override the redirectUri manually, instead of fumbling around and manipulating the "currentUrl" and replace the non query part with the expected redirectUri.

### Version

6.1.3

### Runtime

Node.js

### Runtime Details

22

### Code to reproduce

```js
---
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/openid-client/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
If you want to make a suggestion to improve the API please use the ideas discussion section and please be comprehensive with your suggestions.
