### ISSUE TITLE
Regarding the problem that the Configuration method returns an empty object

### ISSUE THREAD

**Issue by Veclea** [panva/openid-client#731]
### What happened?

I have a test autho well-known url https://dev-nlrbn2g36fhj2yma.us.auth0.com/ which can normally access metadata through the browser. Now I am using version 6.1.4 of openid-client discovery using the discovery method which returns an empty object configuration
![image](https://github.com/user-attachments/assets/9aac8974-8411-4178-840a-38735733f69e)
![image](https://github.com/user-attachments/assets/42bf8d18-4ce9-4c4c-9329-53be35fa1f3a)
![image](https://github.com/user-attachments/assets/498791b8-a04a-4113-a831-f7f47b234fa8)

![image](https://github.com/user-attachments/assets/5e247719-3cee-41af-a58b-ef96f5ac48b8)
I have provided screenshots of the code running results in order. Is this the expected behavior?

### Version

6.1.4 

### Runtime

Browser

### Runtime Details

nodejs 23.2..0  chrome latest  os： win11 24h2

### Code to reproduce

```js
See screenshot I only added part of the print in the build code
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/openid-client/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
It's not empty, it's just that its properties are intentionally hidden away.

**Comment by jimbali** [comment]
`console.log(config.serverMetadata());` seems to do the trick for debugging purposes
