### ISSUE TITLE
user-agent header causing some oidc discovery urls from getting blocked

### ISSUE THREAD

**Issue by deepakprabhakara** [panva/openid-client#732]
### What happened?

The introduction of the user-agent header here - https://github.com/panva/openid-client/blob/main/src/index.ts#L14 is causing some enterprise gateways to block the fetch of the oidc discovery URL. There should be a way to override this and choose not to send the user-agent header to prevent this. Unfortunately this is way more common in enterprise gateways than we'd like so this seems to be the only way forward.

### Version

v6.1.3

### Runtime

Node.js

### Runtime Details

node 20.18.1

### Code to reproduce

```js
I am unable to disclose the discovery URLs this fails on but it is a recurrent issue for us with the library update.
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/openid-client/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
You can use the customFetch extension point to override anything about the requests.

**Comment by deepakprabhakara** [comment]
@panva Many thanks for the tip, will look into customFetch.

**Comment by deepakprabhakara** [comment]
@panva Definitely something different in v6 because v5 works fine with that gateway, was the exact same user agent being sent with v5 as well?

**Comment by panva** [comment]
https://github.com/panva/openid-client/blob/45c96f67ce0644bd829f61e82fba3dd8c051c89e/lib/helpers/request.js#L43
