### ISSUE TITLE
Client can't be used with a variety of Azure endpoints

### ISSUE THREAD

**Issue by Stono** [panva/openid-client#742]
### What happened?

Hey, 
Trying to upgrade from v5 to v6 and hitting "discovered metadata issuer does not match the expected issuer".

Looking at this a bit more, I squarely blame microsoft for their inconsistent endpoints, however... 

- `https://login.windows.net/{tenant}/v2.0/.well-known/openid-configuration` returns `https://login.microsoftonline.com` as the issuer (fail)
- `https://login.windows.net/{tenant}/.well-known/openid-configuration` returns `https://sts.windows.net` as the issuer (fail)
- `https://sts.windows.net/{tenant}/.well-known/openid-configuration` returns `https://sts.windows.net` as the issuer (ok but legacy endpoint)
- `https://sts.windows.net/{tenant}/v2.0/.well-known/openid-configuration` returns `https://login.microsoftonline.com` as the issuer (fail)
- `https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration` returns `https://login.microsoftonline.com` as the issuer (ok) 

Subsequently the only endpoint you can use is the v1 `sts.windows.net` endpoint because it's the only one that actually matches, none of the v2 endpoints are compatible.

I'm not sure how best to move forward with "fixing" it either, I noticed in the code you have `handleEntraId` and `handleB2Clogin` which seem to have some domain specific logic, but unsure if all this complexity should live in `opend-client` code base or instead it's extended with a validator function the user can override, or perhaps a list of permitted issuers for a given endpoint?

### Version

v6.1.7

### Runtime

Node.js

### Runtime Details

v22

### Code to reproduce

```js
this.cachedConfig = await discovery(
      issuer,
      credentials.clientId,
      credentials.clientSecret,
      ClientSecretPost(credentials.clientSecret)
    )
```
```


### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/openid-client/blob/main/CODE_OF_CONDUCT.md)

**Comment by Stono** [comment]
Alright so slight update i got things working with `login.microsoftonline.com` (for some strange reason you have to append /.default to your scope), so for anyone fighting azure here then migrating to that "fixes" it - but i'd imagine there are some people that can't so the extensibility question is still open

**Comment by panva** [comment]
If you want you can skip issuer validation during discovery by passing the discovery url endpoint as the URL instead of the issuer identifier.

The window for more MS-specific workarounds, let alone legacy endpoint ones, is closed, because as soon as you handle one of their non-conform endpoints, three more pop up.

**Comment by Stono** [comment]
> The window for more MS-specific workarounds, let alone legacy endpoint ones, is closed, because as soon as you handle one of their non-conform endpoints, three more pop up.

Yip agree and to be clear, certainly wasn't advocating that.

> If you want you can skip issuer validation during discovery by passing the discovery url endpoint as the URL instead of the issuer identifier.

Fair enough if there's a work around, is that / should that be documented somewhere?  Or are you happy for this GitHub issue to act as that doco (assuming people will search for it when they run into microsoft related issues too?).

**Comment by panva** [comment]
There's a note hinting at disabling discovery issuer value validation in the docs now, I'm happy with that.

> https://github.com/panva/openid-client/blob/54c11eb4a5b29fdfd234605b23c7815bcb304866/docs/functions/discovery.md

**Comment by Stono** [comment]
I don't believe people running into issues migrating from v5 to v6 against Microsoft will make a correlation to that to be honest, but I'm getting vibes you aren't bothered at all which is your prerogative.

(And to be clear I would have happily contributed to improving this to help others).
