### ISSUE TITLE
Bug in Passport strategy's computation of current URL

### ISSUE THREAD

**Issue by delfuego** [panva/openid-client#743]
### What happened?

There appears to be a minor bug in the [Passport strategy's `currentUrl()` function](https://github.com/panva/openid-client/blob/54c11eb4a5b29fdfd234605b23c7815bcb304866/src/passport.ts#L403-L405) that omits the port number from the URLs that it returns. In my case, this meant that as I was trying to migrate to v6 of `openid-client`, I kept getting errors saying that the redirect_uri didn't match the expected redirect URI. After debugging it, it turned out that that was where the issue was arising — in my dev environment, my server runs on a nonstandard port, so my redirect_uri setting was `https://localhost:9443/openid-connect-login` but `currentUrl()` was returning `https://localhost/openid-connect-login`.

I've been able to work around this for now by overriding `currentUrl()` in my instantiated strategy so that it includes the port number. But it's probably worth including that in the default `currentUrl()` implementation; this can be achieved by replacing `${req.host}` with `${req.headers.host}`, which should always include the port if it's nonstandard. 

### Version

v6.1.7

### Runtime

Node.js

### Runtime Details

v22.12.0

### Code to reproduce

```js
let oidcServerConfig = await oidcClient.discovery(new URL('https://discoverUrl'), 'clientId', 'clientSecret');
const strategyOptions = {
  config: oidcServerConfig,
  scope: 'openid profile email custom_claims',
  passReqToCallback: true,
  callbackURL: 'https://localhost:9443/openid-connect-login',
};
const labshareStrategy = new Strategy(strategyOptions, verifyCallback);
passport.use(labshareStrategy);
```

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/openid-client/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Please use the search function in GitHub's UI.
